# Generated by Django 3.2.25 on 2025-11-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexamrecord',
            name='rewarded',
            field=models.BooleanField(default=False),
        ),
    ]
